### ISSUE TITLE
Error in CloudConvert::merge

### ISSUE THREAD

**Issue by riazXrazor** [robbiepaul/cloudconvert-laravel#65]
I'm using the code below
```
$files = [
            'https://cloudconvert.com/assets/d04a9878/testfiles/pdfexample1.pdf',
            'https://cloudconvert.com/assets/d04a9878/testfiles/pdfexample2.pdf'
        ];
        try {
        CloudConvert::merge($files)
           ->to(public_path('countries-agencies-excels/merge.pdf'));

        // CloudConvert::website('www.nyan.cat')->to(public_path('countries-agencies-excels/merge.jpg'));
        } catch(\Exception $e){
            echo $e->getMessage();
            echo $e->getTraceAsString();
        }

```

Error response
```
Client error: `POST https://mariela.infra.cloudconvert.com/process/7ae7417d-2797-4801-8dbf-5983f09356ba` resulted in a `400 Bad Request` response:
{"id":"7ae7417d-2797-4801-8dbf-5983f09356ba","url":"//mariela.infra.cloudconvert.com/process/7ae7417d-2797-4801-8dbf-598 (truncated...)
#0 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#10 /home/razor/Documents/rimsys_dev_v2/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('post', 'https://mariela...', Array)
#11 /home/razor/Documents/rimsys_dev_v2/vendor/robbiep/cloudconvert-laravel/src/RobbieP/CloudConvertLaravel/HttpClientAdapter/Guzzle6Adapter.php(40): GuzzleHttp\Client->__call('post', Array)
#12 /home/razor/Documents/rimsys_dev_v2/vendor/robbiep/cloudconvert-laravel/src/RobbieP/CloudConvertLaravel/Process.php(60): RobbieP\CloudConvertLaravel\HttpClientAdapter\Guzzle6Adapter->post('https://mariela...', Array, Array)
#13 /home/razor/Documents/rimsys_dev_v2/vendor/robbiep/cloudconvert-laravel/src/RobbieP/CloudConvertLaravel/Process.php(77): RobbieP\CloudConvertLaravel\Process->process(Array)
#14 /home/razor/Documents/rimsys_dev_v2/vendor/robbiep/cloudconvert-laravel/src/RobbieP/CloudConvertLaravel/CloudConvert.php(253): RobbieP\CloudConvertLaravel\Process->convert(Array, Object(RobbieP\CloudConvertLaravel\ConvertLocalFile))
#15 /home/razor/Documents/rimsys_dev_v2/vendor/robbiep/cloudconvert-laravel/src/RobbieP/CloudConvertLaravel/CloudConvert.php(650): RobbieP\CloudConvertLaravel\CloudConvert->convertFile()
#16 /home/razor/Documents/rimsys_dev_v2/vendor/robbiep/cloudconvert-laravel/src/RobbieP/CloudConvertLaravel/CloudConvert.php(243): RobbieP\CloudConvertLaravel\CloudConvert->convertFileAndSaveTo()
#17 /home/razor/Documents/rimsys_dev_v2/vendor/robbiep/cloudconvert-laravel/src/RobbieP/CloudConvertLaravel/CloudConvert.php(155): RobbieP\CloudConvertLaravel\CloudConvert->save()
#18 /home/razor/Documents/rimsys_dev_v2/app/Console/Commands/PdfMergeTest.php(47): RobbieP\CloudConvertLaravel\CloudConvert->to('/home/razor/Doc...')
#19 [internal function]: App\Console\Commands\PdfMergeTest->handle()
#20 /home/razor/Documents/rimsys_dev_v2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#21 /home/razor/Documents/rimsys_dev_v2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /home/razor/Documents/rimsys_dev_v2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#23 /home/razor/Documents/rimsys_dev_v2/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#24 /home/razor/Documents/rimsys_dev_v2/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\Container\Container->call(Array)
#25 /home/razor/Documents/rimsys_dev_v2/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#26 /home/razor/Documents/rimsys_dev_v2/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#27 /home/razor/Documents/rimsys_dev_v2/vendor/symfony/console/Application.php(908): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /home/razor/Documents/rimsys_dev_v2/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\PdfMergeTest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /home/razor/Documents/rimsys_dev_v2/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /home/razor/Documents/rimsys_dev_v2/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /home/razor/Documents/rimsys_dev_v2/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /home/razor/Documents/rimsys_dev_v2/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 {main}
```

**Comment by riazXrazor** [comment]
got it array format should be
```
[
     "0" => "https://cloudconvert.com/assets/e214b299/testfiles/pdfexample1.pdf",
      "1" => "https://cloudconvert.com/assets/e214b299/testfiles/pdfexample2.pdf",
]
```
